- hosts: localhost
  gather_facts: no
  roles:
  - role: infra_azure
    vars:
      rg_name: mdavis-ignite2017

- hosts: vmtype_webserver
  roles:
  - role: eShopOnWeb

  tasks:
  - debug:
      msg: 'Host endpoint http://{{ ansible_host }}:5106/'